name: Build APKs
run-name: Build APKs
on:
  workflow_dispatch: {}
jobs:
  Build_Android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        
    - name: Setup Android Signing
      run: |
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/keystore.jks
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/local.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/local.properties
        
    - name: Build APKs
      run: flutter build apk --split-per-abi

    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: artifact-arm64-v8a
        path: ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

    - name: Upload armabi-v7a APK
      uses: actions/upload-artifact@v4
      with:
        name: artifact-armabi-v7a
        path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

    - name: Upload x86_64 APK
      uses: actions/upload-artifact@v4
      with:
        name: artifact-x86_64
        path: ./build/app/outputs/flutter-apk/app-x86_64-release.apk

    - name: Upload universal APK
      uses: actions/upload-artifact@v4
      with:
        name: artifact-universal
        path: ./build/app/outputs/flutter-apk/app-release.apk
        
  upload-release:
    if: ${{ !contains(github.ref, '+') }}
    permissions: write-all
    needs: [ Build_Android ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: artifact-*
          merge-multiple: true

      - name: Pre Release
        run: |
          sudo apt install jq
          curl -s https://api.github.com/repos/wgh136/PicaComic/releases/latest | jq -r '.body' > release.md
          r_tag_name=$(curl -s https://api.github.com/repos/wgh136/PicaComic/releases/latest | jq -r '.tag_name')

      - name: Rename
        run: |
          cp ./build/app/outputs/flutter-apk/*.sha1 ./dist
          cd ./dist
          version=${r_tag_name:1}
          for file in *.apk; do
              if [[ $file =~ ^app-(.*)-release\.apk(.*)$ ]]; then
                  new_name="PicaComic-$version-${BASH_REMATCH[1]}.apk${BASH_REMATCH[2]}"
                  mv "$file" "$new_name"
              fi
          done
          mv app-release.apk "PicaComic-$version-universal.apk"
          cd ..
            
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
          tag_name: $r_tag_name
          body_path: './release.md'
