name: Build APKs
run-name: Build APKs
on:
  workflow_dispatch: {}
jobs:
  Build_Android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        
    - name: Setup Android Signing
      run: |
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/keystore.jks
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/local.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/local.properties
        
    - name: Build APKs
      run: flutter build apk --split-per-abi

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: apps
        path: ./build/app/outputs/flutter-apk
        retention-days: 1
        overwrite: true
        
  upload-release:
    if: ${{ !contains(github.ref, '+') }}
    permissions: write-all
    needs: [ Build_Android ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: apps
          merge-multiple: true

      - name: Rename
        run: |
          cd ./dist
          for file in *.apk; do
            new_name=$(echo $file | sed 's/app-\(.\+\)-release\.apk/\1.apk/')
            mv "$file" "$new_name"
          done
          mv app-release.apk universal.apk
          cd ..
          
      - name: Pre Release
        run: |
          apt install jq
          curl -s https://api.github.com/repos/wgh136/PicaComic/releases/latest | jq -r '.body' > release.md
          r_tag_name=$(curl -s https://api.github.com/repos/wgh136/PicaComic/releases/latest | jq -r '.tag_name')
  
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
          tag_name: r_tag_name
          body_path: './release.md'
