name: Release test
run-name: Release test
on:
  workflow_dispatch: {}
jobs:
  upload-release:
    if: ${{ !contains(github.ref, '+') }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: 11064495916
          path: ./dist/
          name: artifact-.*
          name_is_regexp: true

      - name: Pre Release
        run: |
          sudo apt install jq
          curl -s https://api.github.com/repos/wgh136/PicaComic/releases/latest | jq -r '.body' > release.md
          r_tag_name=$(curl -s https://api.github.com/repos/wgh136/PicaComic/releases/latest | jq -r '.tag_name')
          echo $r_tag_name

      - name: Rename
        run: |
          cd ./dist
          version=${r_tag_name:1}
          echo $version
          for file in *.apk; do
              if [[ $file =~ ^app-(.*)-release\.apk$ ]]; then
                  new_name="PicaComic-$version-${BASH_REMATCH[1]}.apk"
                  mv "$file" "$new_name"
              fi
          done
          mv app-release.apk "PicaComic-$version-universal.apk"
          cd ..
